# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ApplicationWindow(object):
    def setupUi(self, ApplicationWindow):
        ApplicationWindow.setObjectName("ApplicationWindow")
        ApplicationWindow.resize(674, 611)
        self.groupBox_2 = QtWidgets.QGroupBox(ApplicationWindow)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 77, 421, 151))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.login = QtWidgets.QPushButton(self.groupBox_2)
        self.login.setGeometry(QtCore.QRect(330, 110, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.login.setFont(font)
        self.login.setObjectName("login")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 70, 111, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(20, 40, 111, 21))
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(140, 40, 261, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 70, 261, 21))
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.groupBox_3 = QtWidgets.QGroupBox(ApplicationWindow)
        self.groupBox_3.setGeometry(QtCore.QRect(450, 77, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.balance = QtWidgets.QLabel(self.groupBox_3)
        self.balance.setGeometry(QtCore.QRect(10, 20, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.balance.setFont(font)
        self.balance.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.balance.setObjectName("balance")
        self.groupBox_4 = QtWidgets.QGroupBox(ApplicationWindow)
        self.groupBox_4.setGeometry(QtCore.QRect(450, 177, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox.setGeometry(QtCore.QRect(30, 20, 151, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.progressBar = QtWidgets.QProgressBar(ApplicationWindow)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(10, 570, 211, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.groupBox_15 = QtWidgets.QGroupBox(ApplicationWindow)
        self.groupBox_15.setGeometry(QtCore.QRect(10, 237, 651, 291))
        self.groupBox_15.setObjectName("groupBox_15")
        self.bulletin = QtWidgets.QListWidget(self.groupBox_15)
        self.bulletin.setGeometry(QtCore.QRect(10, 20, 631, 261))
        self.bulletin.setObjectName("bulletin")
        self.groupBox_5 = QtWidgets.QGroupBox(ApplicationWindow)
        self.groupBox_5.setGeometry(QtCore.QRect(450, 127, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.profit = QtWidgets.QLabel(self.groupBox_5)
        self.profit.setGeometry(QtCore.QRect(10, 20, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.profit.setFont(font)
        self.profit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.profit.setObjectName("profit")
        self.do_start = QtWidgets.QPushButton(ApplicationWindow)
        self.do_start.setGeometry(QtCore.QRect(580, 570, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.do_start.setFont(font)
        self.do_start.setObjectName("do_start")
        self.do_stop = QtWidgets.QPushButton(ApplicationWindow)
        self.do_stop.setGeometry(QtCore.QRect(490, 570, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.do_stop.setFont(font)
        self.do_stop.setObjectName("do_stop")
        self.loading_msg = QtWidgets.QLabel(ApplicationWindow)
        self.loading_msg.setGeometry(QtCore.QRect(10, 540, 341, 31))
        self.loading_msg.setText("")
        self.loading_msg.setObjectName("loading_msg")
        self.clock = QtWidgets.QLabel(ApplicationWindow)
        self.clock.setGeometry(QtCore.QRect(390, 540, 271, 31))
        self.clock.setText("")
        self.clock.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.clock.setObjectName("clock")
        self.do_resume = QtWidgets.QPushButton(ApplicationWindow)
        self.do_resume.setGeometry(QtCore.QRect(380, 570, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.do_resume.setFont(font)
        self.do_resume.setObjectName("do_resume")
        self.english = QtWidgets.QLabel(ApplicationWindow)
        self.english.setGeometry(QtCore.QRect(20, 30, 341, 21))
        self.english.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.english.setObjectName("english")
        self.download = QtWidgets.QPushButton(ApplicationWindow)
        self.download.setGeometry(QtCore.QRect(570, 22, 91, 31))
        self.download.setObjectName("download")
        self.publicInfo = QtWidgets.QLabel(ApplicationWindow)
        self.publicInfo.setGeometry(QtCore.QRect(20, 10, 381, 61))
        self.publicInfo.setText("")
        self.publicInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.publicInfo.setObjectName("publicInfo")

        self.retranslateUi(ApplicationWindow)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ApplicationWindow)

    def retranslateUi(self, ApplicationWindow):
        _translate = QtCore.QCoreApplication.translate
        ApplicationWindow.setWindowTitle(_translate("ApplicationWindow", "Dives"))
        self.groupBox_2.setTitle(_translate("ApplicationWindow", "IQ Option Login"))
        self.login.setText(_translate("ApplicationWindow", "Ok"))
        self.label_5.setText(_translate("ApplicationWindow", "Password"))
        self.label_6.setText(_translate("ApplicationWindow", "Email"))
        self.groupBox_3.setTitle(_translate("ApplicationWindow", "Balance"))
        self.balance.setText(_translate("ApplicationWindow", "$ 0.00"))
        self.groupBox_4.setTitle(_translate("ApplicationWindow", "Environment"))
        self.comboBox.setItemText(0, _translate("ApplicationWindow", "DEMO"))
        self.comboBox.setItemText(1, _translate("ApplicationWindow", "REAL"))
        self.groupBox_15.setTitle(_translate("ApplicationWindow", "Bulletin Board"))
        self.groupBox_5.setTitle(_translate("ApplicationWindow", "Profit"))
        self.profit.setText(_translate("ApplicationWindow", "$ 0.00"))
        self.do_start.setText(_translate("ApplicationWindow", "Start"))
        self.do_stop.setText(_translate("ApplicationWindow", "Stop"))
        self.do_resume.setText(_translate("ApplicationWindow", "Resume"))
        self.english.setText(_translate("ApplicationWindow", "Checking the latest version... 최신 버전 확인 중..."))
        self.download.setText(_translate("ApplicationWindow", "Download"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ApplicationWindow = QtWidgets.QDialog()
    ui = Ui_ApplicationWindow()
    ui.setupUi(ApplicationWindow)
    ApplicationWindow.show()
    sys.exit(app.exec_())

